const _VIDEO_BUILD_TEMPLATE = {
    mediaPlayer: "",
    mediaType: "",
    media: {
        artist: [{
            src: ""
        }],
        album: "",
        artwork: "",
    },
    disabled: true,
    initialMode: "",
    initialState: true,
    debug: true,
    src: "",
    sources: [],
    tracks: [],
    playlist: [{
        media: {
            artist: [{
                src: ""
            }],
            album: "",
            artwork: "",
        },
        src: "", 
        sources: [], 
        tracks: [], 
        settings: {
            previewImages: {
                address: "", 
                fps: 0
            } || true,
            startTime: 0,
            endTime: 0,
        }
    }],
    settings: {
        allowOverride: [] || true,
        previewImages: {
            address: "", 
            fps: 0
        } || true,
        beta: [],
        modes: [],
        controllerStructure: [] || true,
        timelinePosition: "",
        timeFormat: "",
        startTime: null | 0,
        endTime: null | 0,
        timeSkip: 0,
        volumeSkip: 0,
        brightnessSkip: 0,
        playbackRateSkip: 0,
        automoveCountdown: 0,
        maxBrightness: 0,
        maxVolume: 0,
        maxPlaybackRate: 0,
        notifiers: true,
        progressBar: true,
        persist: true,
        automove: true,
        autocaptions: true,
        autoplay: true,
        loop: true,
        muted: true,
        playsInline: true,
        overlayRestraint: 0,
        keyOverrides: [],
        shiftKeys: [],
        altKeys: [],
        ctrlKeys: [],
        keyShortcuts: {
            prev: "", 
            next: "",
            playPause: "",
            timeFormat: "",
            skipBwd: "",
            skipFwd: "",
            mute: "",
            dark: "",
            volumeUp: "",
            volumeDown: "",
            brightnessUp: "",
            brightnessDown: "",
            playbackRateUp: "",
            playbackRateDown: "",
            objectFit: "",
            fullScreen: "",
            theater: "",
            expandMiniPlayer: "",
            removeMiniPlayer: "",
            pictureInPicture: "",
            captions: "",
            settings: ""
        },
    },
}